package com.enuri.nielsen.admin.repository.shoppingDiary;

import com.enuri.nielsen.admin.domain.shoppingDiary.BuyHistoryRegisteredInShoppingDiary;
import com.enuri.nielsen.admin.domain.shoppingDiary.compositePrimaryKeyClass.BuyHistoryRegisteredInShoppingDiaryId;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface BuyHistoryRegisteredInShoppingDiaryRepository extends BuyHistoryRegisteredInShoppingDiaryRepositoryExtension, JpaRepository<BuyHistoryRegisteredInShoppingDiary, BuyHistoryRegisteredInShoppingDiaryId> {
}
